-- 项目库立项表（迁入芋道后执行；可按租户规范加 tenant_id / creator 等字段）
CREATE TABLE IF NOT EXISTS `project_agent_project` (
  `id`              varchar(64)  NOT NULL COMMENT '主键',
  `project_code`    varchar(64)  DEFAULT NULL,
  `project_name`    varchar(200) NOT NULL,
  `project_type`    varchar(64)  DEFAULT NULL,
  `owner`           varchar(64)  DEFAULT NULL,
  `department`      varchar(128) DEFAULT NULL,
  `sponsor`         varchar(64)  DEFAULT NULL,
  `start_date`      varchar(32)  DEFAULT NULL,
  `end_date`        varchar(32)  DEFAULT NULL,
  `budget`          decimal(18,2) DEFAULT 0,
  `priority`        varchar(16)  DEFAULT NULL,
  `risk_level`      varchar(16)  DEFAULT NULL,
  `members`         varchar(512) DEFAULT NULL,
  `description`     text,
  `goals`           text,
  `source_file`     varchar(255) DEFAULT NULL,
  `remark`          varchar(1000) DEFAULT NULL,
  `status`          varchar(32)  NOT NULL DEFAULT 'draft',
  `created_by`      varchar(64)  DEFAULT NULL,
  `reviewer`        varchar(64)  DEFAULT NULL,
  `review_comment`  varchar(1000) DEFAULT NULL,
  `rag_item_pk`     varchar(128) DEFAULT NULL,
  `submitted_at`    datetime     DEFAULT NULL,
  `reviewed_at`     datetime     DEFAULT NULL,
  `create_time`     datetime     DEFAULT NULL,
  `update_time`     datetime     DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_code` (`project_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Project Agent 项目库';
